In [1]:
import numpy as np
print(np.version)

<module 'numpy.version' from 'C:\\Users\\DEEPIKA\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [4]:
import numpy as np
print(np.__version__)

1.18.1


In [12]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
type(arr)

[1 2 3 4 5]


numpy.ndarray

In [13]:
arr=np.array((1,2,3,4,5))
print(arr)

[1 2 3 4 5]


In [14]:
arr=np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [15]:
arr.shape

(20,)

In [16]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [14]:
arr=np.arange(10).reshape(2,5)
print(arr)
print(arr.shape)
arr.shape

[[0 1 2 3 4]
 [5 6 7 8 9]]
(2, 5)


(2, 5)

In [9]:
#reshaping using list ndarray
import numpy as np

ar = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = ar.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [11]:
newarr.shape

(4, 3)

In [12]:
print(newarr.shape)

(12,)
(4, 3)


In [24]:
arr=np.arange(8).reshape(2,2,2)
print(arr)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [28]:
arr=np.zeros((2,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [30]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1]:
list=[1,2,3,4]
print(list)
list

[1, 2, 3, 4]


[1, 2, 3, 4]

In [2]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [5]:
arr=np.array((1,2,3,4,5))
print(arr)
a=np.array(((1,2),(3,4)))
print(a)

[1 2 3 4 5]
[[1 2]
 [3 4]]


In [4]:
#array with 0 dimensions
arr=np.array(42)
print(arr)
print(arr.shape)

42
()
