In [1]:
#iterating arrays
import numpy as np
arr=np.array([1,2,3,4,5,6,7])
for x in arr:
    print(x)

1
2
3
4
5
6
7


In [3]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [2]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [9]:
arr=np.array([[[1,2,3],[2,3,4]],[[5,6,7],[6,7,8]]])
for i in arr:
    print(i)

for x in arr:
    for y in x:
        print(y)

for x in arr:
    for y in x:
        for z in y:
            print(z)

[[1 2 3]
 [2 3 4]]
[[5 6 7]
 [6 7 8]]
[1 2 3]
[2 3 4]
[5 6 7]
[6 7 8]
1
2
3
2
3
4
5
6
7
6
7
8
