In [21]:
#to check the dimensions
import numpy as ap
a=np.array(42)
b=np.array([1,2,3,4])

print(a)
print(b)

print(a.ndim)
print(b.ndim)


42
[1 2 3 4]
0
1


In [23]:
#to check the dimensions
import numpy as ap

c=np.array([[0,1,3],[2,4,6]])
d=np.array([[[1,2,3],[0,1,2]],[[4,5,6],[7,8,9]]])


print(c)

print(d)


print(c.ndim)
print(d.ndim)


[[0 1 3]
 [2 4 6]]
[[[1 2 3]
  [0 1 2]]

 [[4 5 6]
  [7 8 9]]]
2
3


In [33]:
#to check the dimensions
import numpy as ap
a=np.array(42)
b=np.array([1,2,3,4])
c=np.array([[0,1,3],[2,4,6]])
d=np.array([[[1,2,3],[0,1,2]],[[4,5,6],[7,8,9]]])
e=np.array([[1,2]],[[3,4]],[[5,6]],[[7,8]])
print(a)
print(b)
print(c)
print(c)
print(d)
print(e)
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
print(e.ndim)

ValueError: only 2 non-keyword arguments accepted

In [36]:
import numpy as np
a=np.array([1,2,3,4,5])
print(a)
print(a.shape)
print(a.ndim)
print(a.dtype.name)
print(a.size)
print(a.itemsize)
print(type(a))

[1 2 3 4 5]
(5,)
1
int32
5
4
<class 'numpy.ndarray'>


In [38]:
arr=np.array([1,2,3,4])
print(arr[0])
print(arr[3])
print(arr[2]+arr[3])

1
4
7


In [1]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])
print('5th element on 2nd row: ', arr[1, 4])

# 3d array
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[0,4,7]]])
print(a[0,1,2])

2nd element on 1st row:  2
5th element on 2nd row:  10
6


In [2]:
#negative indexing
print(arr[1,-1])

10


In [5]:
#array slicing
d=np.array([1,2,3,4,5])
print(d[1:3])
print(d[:4])
print(d[1:])
print(d[-5:-2])    #negative slicing
print(d[0:8])
print(d[2:5:2])    #step index
print(d[::3])

[2 3]
[1 2 3 4]
[2 3 4 5]
[1 2 3]
[1 2 3 4 5]
[3 5]
[1 4]


In [7]:
#slicing 2d array
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr)
print(arr[1,0:2])
print(arr[0:2,2])
print(arr[0:2, 1:4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[6 7]
[3 8]
[[2 3 4]
 [7 8 9]]


In [9]:
#conversion
#float to int by using "i" as parameter
import numpy as np
arr=np.array([1.1,2.2,3.1])
newar=arr.astype('i')
print(newar)
print(newar.dtype)
k=arr.astype('int')
print(k)
print(k.dtype)

[1 2 3]
int32
[1 2 3]
int32


In [13]:
#int to boolean
arr = np.array([1, 0, 3])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [14]:
#float to boolean
arr = np.array([1.34, 0.00, 3.00,0.0004])
newarr = arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True  True]
bool


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [16]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)
\

[42  2  3  4  5]
[42  2  3  4  5]


In [17]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [18]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr.shape)

(4,)


In [23]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)
